openapi: 3.0.0
info:
    title: Ecommerce API
    version: 1.0.0
    description: API documentation for the Ecommerce project

paths:
    /api/carts:
        post:
            summary: Crear un nuevo carrito
            tags:
                - Carts
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Cart'
            responses:
                '201':
                    description: Carrito creado exitosamente
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Cart'
                '400':
                    description: Error al crear el carrito
        get:
            summary: Obtener todos los carritos
            tags:
                - Carts
            responses:
                '200':
                    description: Lista de carritos
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Cart'
                '500':
                    description: Error al obtener carritos
        delete:
            summary: Eliminar todos los carritos
            tags:
                - Carts
            responses:
                '200':
                    description: Todos los carritos eliminados
                '500':
                    description: Error al eliminar todos los carritos

    /api/carts/{cid}:
        get:
            summary: Obtener productos de un carrito específico
            tags:
                - Carts
            parameters:
                - in: path
                  name: cid
                  schema:
                      type: string
                  required: true
                  description: ID del carrito
            responses:
                '200':
                    description: Productos del carrito
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/CartProduct'
                '404':
                    description: Carrito no encontrado
                '500':
                    description: Error al obtener productos del carrito

        put:
            summary: Actualizar un carrito completo
            tags:
                - Carts
            parameters:
                - in: path
                  name: cid
                  schema:
                      type: string
                  required: true
                  description: ID del carrito
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Cart'
            responses:
                '200':
                    description: Carrito actualizado
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Cart'
                '404':
                    description: Carrito no encontrado
                '500':
                    description: Error al actualizar el carrito

        delete:
            summary: Vaciar un carrito específico
            tags:
                - Carts
            parameters:
                - in: path
                  name: cid
                  schema:
                      type: string
                  required: true
                  description: ID del carrito
            responses:
                '200':
                    description: Carrito vaciado
                '404':
                    description: Carrito no encontrado
                '500':
                    description: Error al vaciar el carrito

    /api/carts/{cid}/product/{pid}:
        post:
            summary: Agregar un producto a un carrito
            tags:
                - Carts
            parameters:
                - in: path
                  name: cid
                  schema:
                      type: string
                  required: true
                  description: ID del carrito
                - in: path
                  name: pid
                  schema:
                      type: string
                  required: true
                  description: ID del producto
            responses:
                '200':
                    description: Producto añadido al carrito
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Cart'
                '404':
                    description: Carrito o producto no encontrado
                '500':
                    description: Error al añadir el producto al carrito

    /api/carts/{cid}/purchase:
        post:
            summary: Realizar la compra de un carrito
            tags:
                - Carts
            parameters:
                - in: path
                  name: cid
                  schema:
                      type: string
                  required: true
                  description: ID del carrito
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    description: Email del comprador
            responses:
                '200':
                    description: Compra realizada
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    ticket:
                                        $ref: '#/components/schemas/Ticket'
                                    failedProducts:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                productId:
                                                    type: string
                                                availableStock:
                                                    type: number
                '500':
                    description: Error al realizar la compra

    /api/carts/{cid}/products/{pid}:
        put:
            summary: Actualizar cantidad de un producto en el carrito
            tags:
                - Carts
            parameters:
                - in: path
                  name: cid
                  schema:
                      type: string
                  required: true
                  description: ID del carrito
                - in: path
                  name: pid
                  schema:
                      type: string
                  required: true
                  description: ID del producto
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                quantity:
                                    type: number
                                    description: Nueva cantidad del producto
            responses:
                '200':
                    description: Cantidad del producto actualizada
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Cart'
                '404':
                    description: Carrito o producto no encontrado
                '500':
                    description: Error al actualizar la cantidad del producto

        delete:
            summary: Eliminar un producto específico del carrito
            tags:
                - Carts
            parameters:
                - in: path
                  name: cid
                  schema:
                      type: string
                  required: true
                  description: ID del carrito
                - in: path
                  name: pid
                  schema:
                      type: string
                  required: true
                  description: ID del producto
            responses:
                '200':
                    description: Producto eliminado del carrito
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Cart'
                '404':
                    description: Carrito o producto no encontrado
                '500':
                    description: Error al eliminar el producto del carrito

components:
    schemas:
        Cart:
            type: object
            properties:
                id:
                    type: string
                    description: ID del carrito
                products:
                    type: array
                    items:
                        $ref: '#/components/schemas/CartProduct'
        CartProduct:
            type: object
            properties:
                product:
                    type: string
                    description: ID del producto
                quantity:
                    type: number
                    description: Cantidad del producto
        Ticket:
            type: object
            properties:
                code:
                    type: string
                    description: Código del ticket
                purchaser:
                    type: string
                    description: Email del comprador
                amount:
                    type: number
                    description: Monto total de la compra
